# This file was generated by GoReleaser. DO NOT EDIT.
cask "tz" do
  desc "Realtime timezone viewer CLI"
  homepage "https://github.com/demarsdouglas/tz-cli"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tz"

  on_macos do
    on_intel do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.4/tz-darwin-amd64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "2db49a3d4dd115fe58ff2f39b74037d8523f1a339e80bfd4c152ea699cec2888"
    end
    on_arm do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.4/tz-darwin-arm64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "8c546caadf6fd00adca7fe072ac82cf33eac4fee5d30555acba2d377f6fd41d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.4/tz-linux-amd64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "700aefb95fb818c7b36a6ceb7636750a96bbd7df480c740dcb8fb95e26462dcb"
    end
    on_arm do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.4/tz-linux-arm64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "89a2539e1418ab406542946c1dc970bc9ef10245127213c974339242b7bf6645"
    end
  end

  # No zap stanza required
end
