# This file was generated by GoReleaser. DO NOT EDIT.
cask "tz" do
  desc "Realtime timezone viewer CLI"
  homepage "https://github.com/demarsdouglas/tz-cli"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tz"

  on_macos do
    on_intel do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.3/tz-darwin-amd64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "6e9f8e2bd592282a0f633f4aaf67822e89d5b40ca6eb9b350035afc8c619da38"
    end
    on_arm do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.3/tz-darwin-arm64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "e8da289537a40dcee44207e6bdeead16117475bcf9f8c65aa73410cddf039f7c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.3/tz-linux-amd64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "c4513c9b1db7577e031f186b2851cb2e5ff215680e3c5ca44d5878075e56b4b7"
    end
    on_arm do
      url "https://github.com/demarsdouglas/tz-cli/releases/download/v1.0.3/tz-linux-arm64.tar.gz",
        verified: "github.com/demarsdouglas/tz-cli"
      sha256 "e044f7697292ed22dd9b250390794c406a1504b3f5d37f6f41f15d41a1a70586"
    end
  end

  # No zap stanza required
end
